/**
 * Circle of Life 主题配置
 * 视觉 token 默认对齐封面工具 theme-ink（宣纸 + 朱砂）
 */
const CONFIG = {
  // 墨弧 Ink
  CIRCLELIFE_COLOR_BG: '#F5F0E4',
  CIRCLELIFE_COLOR_SURFACE: '#FCFAF4',
  CIRCLELIFE_COLOR_TEXT: '#20190F',
  CIRCLELIFE_COLOR_MUTED: '#57493A',
  CIRCLELIFE_COLOR_BORDER: 'rgba(32,25,15,0.13)',
  CIRCLELIFE_COLOR_ACCENT: '#B24A33',

  CIRCLELIFE_MENU_CATEGORY: true,
  CIRCLELIFE_MENU_TAG: true,
  CIRCLELIFE_MENU_ARCHIVE: true,
  CIRCLELIFE_MENU_SEARCH: true,

  /** 首页按日时间线（贴合「时光的弧线」） */
  CIRCLELIFE_HOME_TIMELINE: true,
  CIRCLELIFE_HOME_LATEST_CARD: true,
  CIRCLELIFE_SIDEBAR_ONLY_ON_POST: true,

  CIRCLELIFE_POST_LIST_COVER: false,
  CIRCLELIFE_TITLE_IMAGE: false,
  CIRCLELIFE_HOME_MINIMAL_HEADER: true,

  CIRCLELIFE_ARTICLE_LAYOUT_VERTICAL: false,
  CIRCLELIFE_ARTICLE_HIDDEN_NOTIFICATION: false
}
export default CONFIG
